a = input('Digite algo: ')
print('O tipo primitivo desse valor é ', type(a))
print('Só tem espaços? ', a.isspace())
print('ë um numero?', a.isnumeric())
print('É alfabetico?', a.isalpha())
print('É alfanumerico? ', a.isalnum())
print('Está em maiúsculo?', a.isupper())
print('Esta em minuscula?', a.islower())